### ISSUE TITLE
Where did I go wrong? :)

### ISSUE THREAD

**Issue by cormullion** [attobot/attobot#2]
I had a go at this: I registered packages with Autobot:

![screen shot 2016-12-05 at 08 42 57](https://cloud.githubusercontent.com/assets/52289/20878436/deb61c1c-bac6-11e6-9d05-87e78f242441.png)

then:

```
julia> using PkgDev
julia> PkgDev.tag("ColorSchemes", :minor)
INFO: Tagging ColorSchemes v1.2.0
INFO: Committing METADATA for ColorSchemes

shell> git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

shell> git push
Everything up-to-date

shell>  git push origin --tags
Counting objects: 1, done.
Writing objects: 100% (1/1), 171 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To github.com:cormullion/ColorSchemes.jl.git
 * [new tag]         v1.2.0 -> v1.2.0
```

That's all I have to do? What happens now?

**Comment by simonbyrne** [comment]
You need to use the [GitHub releases](https://help.github.com/articles/creating-releases/) interface.

A GitHub release is some extra functionality built on top of a git tag (e.g. creating release notes and storing binaries, as well as having an easy-to-capture webhook that attobot can use).

1. Go to https://github.com/cormullion/ColorSchemes.jl/releases
2. Select "Draft a new release". 
3. Enter the tag name: it can either be an existing tag (which in this case you just created), or you can enter a new name and it will create a tag (this was the main intention, so that you don't need to use `PkgDev`). 
4. Fill in any other details you like (optional)
5. Click  "Publish release" and you're done.

**Comment by cormullion** [comment]
Ah, OK. Thanks. Learn something new every day...:)

**Comment by simonbyrne** [comment]
No worries, the release stuff is a bit non-obvious. I've expanded the README: would you mind having a look over it and let me know if anything is still unclear?

**Comment by cormullion** [comment]
Cool, looks helpful! A confusing aspect of git-development for me is knowing what to do locally and what to do on GitHub (and how to synchronise the two). So it looks like you can tag a release locally, push it, then use it to make a new release on GitHub/Draft a new release/, or —preferred?— make a new release entirely on GitHub.

**Comment by simonbyrne** [comment]
Yes, that's the idea.

One thing I am considering is moving it to use tags instead of releases, but this will require creating a new integration as I can't change the permissions retrospectively. The benefit would be that local `git tag` + `git push --tags` would be sufficient (and you could still continue to use releases as before). As a user, do you think this would be preferable?

The only downside that I can think of is that it increases the risk of accidents (it's much easier to accidentally push tags compared with creating a release).

**Comment by cormullion** [comment]
Yes, I like the idea of using the tags locally. Can't comment on the risk of accidents - there are many ways to get into trouble using `git` already, so ... :)
