### ISSUE TITLE
rerelease problem [solved]

### ISSUE THREAD

**Issue by DrKrar** [attobot/attobot#23]
I had made a release v.08.4 for [GeoEfficiency](https://github.com/DrKrar/GeoEfficiency.jl/releases/tag/0.8.4) 20 hr ago then I had to delete it and make a commit to the repository then rerelease the version.
for the first part it is all ok. but no action is done on rereleasing even when I edit the release and changed its name.

**Comment by ararslan** [comment]
It sounds like you deleted the release and not the tag. This is what you need to do to re-trigger attobot:

1. Go to the Releases tab
2. Delete the most recent release, v0.8.4
3. Switch to viewing tags instead of releases
4. Delete the tag for v0.8.4
5. Use the GitHub web UI to create a new release v0.8.4. This creates the release and the tag and re-triggers attobot to update the METADATA PR.

These steps are laid out in the README: https://github.com/attobot/attobot/blob/master/README.md

**Comment by DrKrar** [comment]
at first, thanks for providing such a great tool it was a nightmare to update Metadata with new release.
i had edit my new release. https://github.com/DrKrar/GeoEfficiency.jl/issues/2
is this good to make a new release.

**Comment by DrKrar** [comment]
update: it is was my fault, I had dropped the v in the version tag and assumed that just renaming the tag is enough to make update to this metadata pull request.
now all is ok,
